# Generated by Django 4.2.7 on 2024-01-02 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_corousel_product_carousel'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digital',
            field=models.BooleanField(default=False),
        ),
    ]
