# Generated by Django 4.2.7 on 2023-12-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_product_images_product_image1_product_image10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='corousel',
            field=models.ImageField(blank=True, null=True, upload_to='corousel/'),
        ),
    ]
