# Generated by Django 4.2.7 on 2023-12-25 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_product_corousel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='image',
            new_name='image1',
        ),
    ]
