# Generated by Django 4.2.7 on 2023-12-31 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_product_digital'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalProductResource',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='base.product')),
                ('resource_file', models.FileField(blank=True, null=True, upload_to='digital_resources/')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_resource', to='base.product')),
            ],
        ),
    ]
