# Generated by Django 4.2.7 on 2023-12-31 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_digitalproductresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='digitalproductresource',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
