# Generated by Django 4.2.7 on 2024-01-10 05:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_companydetails_startedat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='products',
        ),
        migrations.RemoveField(
            model_name='product',
            name='carousel',
        ),
        migrations.RemoveField(
            model_name='product',
            name='user',
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.companydetails'),
        ),
        migrations.AddField(
            model_name='product',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.companydetails'),
        ),
        migrations.AddField(
            model_name='product',
            name='corousel',
            field=models.ImageField(blank=True, null=True, upload_to='corousel/'),
        ),
    ]
