# Generated by Django 4.2.7 on 2023-12-31 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_digitalproductresource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='digitalResource',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='digital_resources/'),
        ),
        migrations.DeleteModel(
            name='DigitalProductResource',
        ),
    ]
