# Generated by Django 4.2.7 on 2023-12-13 10:02

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_review_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name=base.models.Product),
        ),
    ]
