# Generated by Django 4.2.7 on 2024-01-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_companydetails_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digitalResource',
            field=models.FileField(blank=True, null=True, upload_to='digital_resources/'),
        ),
    ]
