# Generated by Django 4.2.7 on 2023-12-31 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_product_digitalresource_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='../placeholder.png', null=True, upload_to='products/'),
        ),
    ]
