# Generated by Django 4.2.7 on 2024-01-02 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_orderitem_digital'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digitalResource',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='digital_resources/'),
        ),
    ]
