# Generated by Django 4.2.7 on 2024-01-02 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_digitalresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='digitalResource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='base.product'),
        ),
    ]
