# Generated by Django 4.2.7 on 2024-01-02 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_orderitem_digitalresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='digitalResource',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='digital_resources/'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='base.order'),
        ),
    ]
