# Generated by Django 4.2.7 on 2024-01-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_companydetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydetails',
            name='orders',
        ),
    ]
