# Generated by Django 4.2.7 on 2024-02-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_remove_orderitem_digitalresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, default='placeholder/placeholder.png', null=True, upload_to='products/'),
        ),
    ]
