# Generated by Django 4.2.7 on 2024-02-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_product_image1'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='digitalResource',
            field=models.FileField(blank=True, editable=False, null=True, upload_to='order_digital_resources/'),
        ),
    ]
