# Generated by Django 4.2.7 on 2024-02-10 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_orderitem_digitalresource'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='corousel',
            new_name='carousel',
        ),
    ]
