# Generated by Django 4.2.7 on 2024-02-10 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_rename_corousel_product_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carousel',
            field=models.ImageField(blank=True, null=True, upload_to='carousel/'),
        ),
    ]
